class SpecialitiesList{
   static List<String>? specialities = [
    "COVID",
    "Skin & Hair",
    "Women's Health",
    "General Physician","Dental Care",
    "Bones & Joints",
    "Mental Wellness",
    "Ear, Nose, Throat",
    "Sexual Health",
    "Child Specialist",
    "Homeopathy",
    "Digestive Issues",
    "Eye Specialist",
    "Heart",
    "Physiotherapy",
    "Brain and Nerves",
    "Lungs and Breathing",
    "Kidney Issues",
    "General Surgery",
    "Diabetes Management",
    "Ayurveda",
    "Cancer",
    "Urinary Issues",
    "Veterinary",
    "Diet & Nutrition",
    "Physiotherapy",
    "Homeopathy"
        "",
    "Piles/Hemorrhoids",
    "Hernia",
    "Appendicitis",
    "Anal Fissure",
    "Varicose Vein ",
    "Kidney Stone",
    "Gall Stones",
    "Circumcision"
  ];
}
